;; This "home-environment" file can be passed to 'guix home reconfigure'
;; to reproduce the content of your profile.  This is "symbolic": it only
;; specifies package names.  To reproduce the exact same profile, you also
;; need to capture the channels being used, as returned by "guix describe".
;; See the "Replicating Guix" section in the manual.

(use-modules (gnu home)
             (gnu packages)
             (gnu services)
             (guix gexp)
             (gnu home services shells))

(home-environment
 ;; Below is the list of packages that will show up in your
 ;; Home profile, under ~/.guix-home/profile.
 (packages (specifications->packages
            (list "autorandr"
                  "libinput"
                  "eudev"
                  "xinput"
                  "sleuthkit"
                  "glib"
                  "java-cglib"
                  "xournalpp"
                  "xournal"
                  "boot"
                  "gcc-toolchain"
                  "google-chrome-stable"
                  "clang-toolchain"
                  "libbpf-updated"
                  "xscreensaver"
                  "bpftool"
                  "font-inconsolata"
                  "pkg-config"
                  "perf"
                  "pulseaudio-qt"
                  "ncmpcpp"
                  "pavucontrol"
                  "streamlink"
                  "d-feet"
                  "b4"
                  "net-tools"
                  "libnftnl"
                  "mpd"
                  "wacomtablet"
                  "xf86-input-wacom"
                  "libpthread-stubs"
                  "perl"
                  "cmake"
                  "elfutils"
                  "bc"
                  "lld"
                  "clang"
                  "bison"
                  "flex"
                  "libtool"
                  "ncurses"
                  "make"
                  "rust-cargo"
                  "rust"
                  "nyxt"
                  "maven"
                  "sysstat"
                  "obs"
                  "emacs"
                  "gdb"
                  "redshift"
                  "alacritty"
                  "mu"
                  "zstd"
                  "pinentry"
                  "nix"
                  "jack"
                  "carla"
                  "lsof"
                  "otpclient"
                  "ethtool"
                  "gnuradio"
                  "vscodium"
                  "git"
                  "cups"
                  "xclip"
                  "uget"
                  "runc"
                  "cryptsetup-static"
                  "okular"
                  "turbovnc"
                  "openjdk:jdk"
                  "lwjgl3"
                  "xss-lock"
                  "sbcl-stumpwm-clipboard-history"
                  "sbcl-stumpwm-mpd"
                  "sbcl-ubiquitous"
                  "emacs-mpdel"
                  "libxcursor"
                  "sbcl-stumpwm-notify"
                  "sbcl-stumpwm-ttf-fonts"
                  "stumpish"
                  "stm8flash"
                  "java-chromium-embedded-framework"
                  "chromium-embedded-framework"
                  "smartmontools"
                  "fish"
                  "ungoogled-chromium"
                  "netdiscover"
                  "arp-scan"
                  "cataclysm-dda"
                  "icedove"
                  "xchm"
                  "lm-sensors"
                  "telegram-desktop"
                  "linphone-desktop"
                  "flatpak"
                  "xterm"
                  "cloc"
                  "javacpp"
                  "javacpp-modsecurity"
                  "libmodsecurity"
                  "cassandra"
                  "e2fsck-static"
                  "java-swt"
                  "fastboot"
                  "youtube-dl"
                  "youtube-viewer"
                  "java-eclipse-equinox-common"
                  "java-eclipse-osgi"
                  "wireguard-tools"
                  "clojure-tools"
                  "tcpdump"
                  "python-dotmap"
                  "python-pypubsub"
                  "mkp224o"
                  "jtdx"
                  "wsjtx"
                  "virt-manager"
                  "emacs-elpher"
                  "cutter"
                  "unrar"
                  "openvpn"
                  "docker-compose"
                  "adb"
                  "alsa-utils"
                  "vlc"
                  "dia"
                  "steam"
                  "ffmpeg@4.4.1"
                  "openssl@1.1.1l"
                  "patchelf"
                  "audit"
                  "rocksdb"
                  "mpv"
                  "pcmanfm"
                  "thunar"
                  "spacefm"
                  "shotcut"
                  "zrythm"
                  "gimp"
                  "blueman"
                  "calibre"
                  "icecat"
                  "screenfetch"
                  "wireshark"
                  "veracrypt"
                  "quassel"
                  "xmoto"
                  "lxqt-openssh-askpass"
                  "arandr"
                  "xnec2c"
                  "pencil2d"
                  "scribus"
                  "xdotool"
                  "scrot"
                  "keepassxc"
                  "gettext"
                  "ant@1.10.10"
                  "guile-doorbell"
                  "python-nose"
                  "node@14"
                  "xeyes"
                  "bluez"
                  "avahi"
                  "binwalk"
                  "pulsemixer"
                  "htop"
                  "python"
                  "nftables"
                  "nmap"
                  "sbcl"
                  "curl"
                  "vsftpd"
                  "bind:utils"
                  "leiningen"
                  "zip"
                  "guile-hall"
                  "guile-irregex"
                  "i2pd"
                  "protobuf@3.17"
                  "gash"
                  "strace"
                  "hostapd"
                  "sicp"
                  "guile-json@4.5"
                  "socat"
                  "rtl-sdr"
                  "aide"
                  "aspell-dict-en"
                  "mg"
                  "wabt"
                  "axel"
                  "neofetch"
                  "parted@3.4"
                  "progress"
                  "zerotier-one"
                  "screen"
                  "netcat"
                  "kbd"
                  "file"
                  "tmux"
                  "aspell"
                  "tree"
                  "font-hack"
                  "font-fira-code"
                  "unzip"
                  "emacs-telega"
                  "xrandr"
                  "inotify-tools"
                  "cool-retro-term"
                  "kitty"
                  "visualvm"
                  "meshtastic-python"
                  "siglo"
                  "tinyb")))

 ;; Below is the list of Home services.  To search for available
 ;; services, run 'guix home search KEYWORD' in a terminal.
 (services
  (list (service home-bash-service-type
                 (home-bash-configuration
                  (aliases '(("grep" . "grep --color=auto") ("j!" . "jbang")
                             ("ll" . "ls -l")
                             ("ls" . "ls -p --color=auto")))
                  (bashrc
                   (list (local-file
                          "/home/dissoc/Workspace/dissoc-guix-home/.bashrc"
                          "bashrc")))
                  (bash-profile
                   (list (local-file
                          "/home/dissoc/Workspace/dissoc-guix-home/.bash_profile"
                          "bash_profile"))))))))
